import "./globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import React from "react";

export const dynamic = "force-dynamic";
const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next 13 Tutorial",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${rubik.className}`}>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
